name: Deploy Beanstalk Docker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create env
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo SWAGGER_ADMIN=${{ secrets.SWAGGER_ADMIN }} >> .env
          echo SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo SYNCHRONIZE=${{ secrets.SYNCHRONIZE }} >> .env
          echo LOGGING=${{ secrets.LOGGING }}>> .env
          echo DB_CONNECTION_TIMEOUT=${{ secrets.DB_CONNECTION_TIMEOUT }} >> .env
          echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> .env
          cat .env

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x node_modules/\*

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: pog-production-api-${{ github.sha }}
          deployment_package: deploy.zip

      - name: Success
        run: echo deployed successfully.
